##############################################################################
# Content
##############################################################################

# Link to a page that gives an overview of all your projects.
# This can be an external link (e.g., to you GitHub profile) or to another
# page within your website.
projects_url: http://github.com/probberechts

# Set the page direction to RTL or LTR. default is LTR. (if you set it 'rtl', the 'vazir' font will be loaded.)
direction: ltr
# Configure the navigation menu.
# A pair 'Key: url' will result in a link to 'url' with the name 'Key' in the
# navigation menu. Optionally, you can add translations for the 'Key' in
# languages/*.yml
nav:
  home: /
  about: /about/
  articles: /archives/
  search: /Search/
  简/繁: javascript:translatePage();


# Links to your social media accounts.
# The keys should correspond to Fontawesome icon names
# (see https://fontawesome.com/icons?d=gallery&s=brands);
# only 'mail' is an exception.
social_links:
  github: http://github.com/royians
  twitter: https://twitter.com/AlexMTzyj
  telegram: https://t.me/littleDreamlandPlus
  qq: http://sighttp.qq.com/authd?IDKEY=a1feecd44c51315fc4837bd5ead86baff7e786034961a349
  weixin: javascript:alert('我的微信号是 @FM238391，即将带你打开我的二维码');window.open('https://ws1.sinaimg.cn/large/8595b112ly1fw4hatfjc0j20j00pwq7m.jpg');
  mail: mailto:z1294686101@gmail.com

# Customize the overview with displaying a tagcloud on the index page.
# Options: https://hexo.io/docs/helpers.html#tagcloud
tags_overview: true

# Customize the overview with the most recent blog posts on the index page.
# Options:
#   - show_all_posts: whether to show all available posts.
#   - post_count: whether to show only the x most recent posts.
posts_overview:
  show_all_posts: false
  post_count: 8


##############################################################################
# Look and Feel
##############################################################################

# Customize the logo (i.e., the cactus) in the header.
# Options:
#   - enabled: whether to show (true) or hide (false) the logo.
#   - width: width of the logo in pixel units
#   - height: height of the logo in pixel units
#   - url: where the logo can be found
#   - gravatar: whether to use your Gravatar as the logo
logo:
  enabled: true
  width: 50
  height: 50
  url: /images/logo.png
  gravatar: false

# Customize the favicons.
# Cactus supports a limited set of the three most important icons:
#   - desktop: The classic favion.ico file.
#   - android: A 192x192 PNG file.
#   - apple:  A 180x180 PNG file.
# These can be generated with http://realfavicongenerator.net/
# Options:
#   - url: where the icon can be found
#   - gravatar: whether to create a favicon from your Gravatar
favicon:
  desktop:
    url: /images/favicon.ico
    gravatar: false
  android:
    url: /images/favicon-192x192.png
    gravatar: false
  apple:
    url: /images/apple-touch-icon.png
    gravatar: false

# The color scheme that should be used to highlight codeblocks.
# See source/css/_highlight for a list of all available color schemes.
# highlight: rainbow

# Set the color scheme.
# Available color schemes are 'dark', 'light', 'classic' and 'white'.
# Alternatively, add your own custom color scheme to source/css/_colors.
colorscheme: dark

# Maximal width of the page in rem units.
page_width: 48


##############################################################################
# Miscellaneous
##############################################################################

# Enable or disable the RSS feed.
rss: false

# Turn your web pages into graph objects (see http://ogp.me).
open_graph:
  fb_app_id:
  fb_admins:
  twitter_id:
  google_plus:


##############################################################################
# Plugins
##############################################################################

# Fill in your Disqus Comments Shortname to enable Disqus comments.
disqus:
  enabled: false
  shortname: royians

# Fill in your Google Analytics tracking ID to enable Google Analytics.
google_analytics:
  enabled: true
  id: UA-112028390-1

# Fill in your Baidu Analytics tracking ID to enable Baidu Analytics.
baidu_analytics:
  enabled: true
  id: f519f7f19502f59a9d622978cb3f5959

# Fill in you Gravatar user id / email if you want to use your gravatar as the
# logo and/or favicons of you website.
gravatar:
  email: z1294686101@gmail.com

# Valine comment system. https://valine.js.org
valine:
  enable: true # if you want use valine, please set this value to true
  appId: KNcQSontV3macob1AuySeLCI-gzGzoHsz # your leancloud appId
  appKey: XQoDM9LJmKlkjPMJ7WGn2qbU # your leancloud appKey
  notify: false # Mail notify
  verify: false # Verify code
  avatar: retro # Gravatar style : mm/identicon/monsterid/wavatar/retro/hide
  placeholder:  ฅ( ̳• ◡ • ̳)ฅ 来评论呀 # Comment Box placeholder
  guest_info: nick,mail,link # Comment header info
  pageSize: 4 # comment list page size